"--out_dir out/sampling/test1", 
"--ref_path models/evaluation/VIRTUAL_imagenet64_labeled.npz", 
"--teacher_model_path models/stage2_onestep_generator_64x64_to_64x64_ema_0.999_420000_fid_1.21.pt", 
"--data_dir /home/bratosiewicz/datasets/ILSVRC/Data/CLS-LOC/train", 
"--z_no_flip_dir out/imagenet-xz-no-flip/edm_heun_sampler_40_steps_64_ema_itrs_model_ema_7_rho", 
"--z_flip_dir out/imagenet-xz-flip/edm_heun_sampler_40_steps_64_ema_itrs_model_ema_7_rho",
"--model_path models/stage3_onestep_generator_64x64_to_128x128_ema_0.999_100000_fid_1.48.pt", 
"--xz_type=npz",
"--map_location=cuda",
"--device_id=0",
"--use_MPI=True",
"--use_fp16=True",
"--loss_norm=cnn_vit", 
"--decoder_style=unet",
"--training_mode=pgd", 
"--class_cond=True", 
"--microbatch 260", 
"--global_batch_size=260", 
"--batch_size=500", 
"--new=False",
"--decoder_reverse=False",
"--gan_major=True",
"--input_size=64", 
"--image_size=128", 
"--pretrained_output_size=64", 
"--num_workers=16", 
"--sampling_batch=8", 
"--num_heun_step=17", 
"--num_channels=192", 
"--num_head_channels=64", 
"--num_res_blocks=3", 
"--resblock_updown=True", 
"--use_scale_shift_norm=True", 
"--ema_rate=0.999",
"--eval_ode_interval=5000000000", 
"--decoder_gan_frequency=1",
"--num_heun_step_random=False", 
"--heun_step_strategy=weighted", 
"--dev_log=True", 
"--save_png=True", 
"--check_dm_performance=False", 
"--intermediate_samples=True", 
"--eval_fid=True", 
"--eval_similarity=False", 
"--class_cond=True", 
"--load_ode=False", 
"--diffusion_schedule_sampler=lognormal", 
"--p_mean=-1.2", 
"--p_std=1.2", 
"--sigma_max=80.", 
"--rho=7", 
"--diffusion_weight_schedule=karras_weight", 
"--diffusion_type=ve", 
"--pretraining_step=-1", 
"--activate_from=12", 
"--separate_update=False", 
"--recon_discriminator=False", 
"--recon_discriminator_weight=0.2", 
"--decoder_adaptive_weight=True", 
"--decoder_override=True", 
"--superres=False", 
"--progressive=False", 
"--decoder_training=True", 
"--decoder_discriminator_training=True", 
"--discriminator_weight=0.2",
"--port 128", 
"--eval_decoder_interval=1000", 
"--eval_batch=800", 
"--eval_num_samples=50000", 
"--save_period=1000", 
"--save_interval=10000", 
"--sample_interval=1000", 
"--log_interval=100",
"--stochastic_seed=True", 
"--save_format=png", 
"--ind_1=5", 
"--ind_2=3", 
"--sampler=onestep", 
"--sampling_steps=1", 